### ISSUE TITLE
Available for Net Core?

### ISSUE THREAD

**Issue by gkapellmann** [dominicusmento/CSharpTradFriLibrary#53]
Hello, good day!

Just wondering if this project is compatible with .Net Core? I see in te dependencies that it only lists .NetStandard, so I am inclined to believe that is not yet there?

Is this planned in the roadmap?

Thank you for your time!

**Comment by gkapellmann** [comment]
Thank you for your answer, so i could assume then that it will work with .Net Core 6, right?

**Comment by sandervandevelde** [comment]
I did not test it with .Net Core 6 yet.

You can try it yourself of course.

**Comment by gkapellmann** [comment]
Yes, seems to be working fine, I tested deployment to windows x64, Linux x64 and Linux arm.
